### ISSUE TITLE
CMake Error: Could not find the required component 'kr_mav_msgs'. 

### ISSUE THREAD

**Issue by tsrjrc** [KumarRobotics/mrsl_quadrotor#15]
Hello！I have the following problems.Thank you!
-- Could not find the required component 'kr_mav_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "kr_mav_msgs" with
  any of the following names:

    kr_mav_msgsConfig.cmake
    kr_mav_msgs-config.cmake

  Add the installation prefix of "kr_mav_msgs" to CMAKE_PREFIX_PATH or set
  "kr_mav_msgs_DIR" to a directory containing one of the above files.  If
  "kr_mav_msgs" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by ljarin** [comment]
https://github.com/KumarRobotics/mrsl_quadrotor/issues/4#issuecomment-413002540

It is part of an internal repo that's still in the process of being open sourced. See this comment for the messages you need (same as quadrotor_msgs; it was renamed)

**Comment by ge3088** [comment]
Hello, I am encountering the same issue when I run catkin_make and I don't know how to fix it yet. I have created a package called hw6 in src folder. Inside hw6 package I created a folder named "msg" where I added my custom message file. Then I modified the CMakeList.txt and package.xml files properly so catkin knows everything it needs to know about the message I created.


Base path: /home/bilal/catkin_ws
Source space: /home/bilal/catkin_ws/src
Build space: /home/bilal/catkin_ws/build
Devel space: /home/bilal/catkin_ws/devel
Install space: /home/bilal/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/bilal/catkin_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/bilal/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/bilal/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/bilal/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/bilal/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.26
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - hw6
-- ~~  - my_awesome_code
-- ~~  - my_new_package
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'hw6'
-- ==> add_subdirectory(hw6)
-- **Could NOT find message (missing: message_DIR)
-- Could not find the required component 'message'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "message" with any
  of the following names:

    messageConfig.cmake
    message-config.cmake

  Add the installation prefix of "message" to CMAKE_PREFIX_PATH or set
  "message_DIR" to a directory containing one of the above files.  If
  "message" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  hw6/CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/bilal/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/bilal/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:320: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed**

**Comment by ljarin** [comment]
Make sure you follow the instructions here http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv
It looks like cmake is looking for a package called message, when probably the package you meant is message_generation

**Comment by ge3088** [comment]
Indeed, I was missing the underscore (I wrote it as message generation).
Thank you so much, that solved the problem.
